backup_servers

diff --git a/bin/backup_servers b/bin/backup_servers
--- a/bin/backup_servers
+++ b/bin/backup_servers
@@ -115,7 +115,7 @@ Nicolas Boisselier nicolas.boisselier@gmail.com
 "
 }
 
-is_locahost() {
+is_localhost() {
   case $1 in
     127.0.0.1|localhost*) return 0 ;;
     `hostname -s`) return 0 ;;
@@ -162,17 +162,18 @@ backup_dirs() {
   declare lock="$dest_dir/$s.lock"
 	if [ "$DEBUG" = "0" -a "$DRY_RUN" = "0" ] && [ -e "$lock" ]; then
 
-    declare pid=`cat "$lock"`
-
-    if [[ -z `ps -p $pid | sed 1d` ]]; then
-     echo "$s: WARN: delete old lock $lock, pid $pid is not running"
-     rm "$lock"
-
-    else
-      echo "$s: ERR: $lock already exists!"
-      return 2
-
-    fi
+    backup_servers_create_lock "$lock" "$s: " || return
+# root 27.06.19     declare pid=`cat "$lock"`
+# root 27.06.19 
+# root 27.06.19     if [[ -z `ps -p $pid | sed 1d` ]]; then
+# root 27.06.19      echo "$s: WARN: delete old lock $lock, pid $pid is not running"
+# root 27.06.19      rm "$lock"
+# root 27.06.19 
+# root 27.06.19     else
+# root 27.06.19       echo "$s: ERR: $lock already exists!"
+# root 27.06.19       return 2
+# root 27.06.19 
+# root 27.06.19     fi
 	fi
 
   #
@@ -186,12 +187,12 @@ backup_dirs() {
   #
   # Create Lock
   #
-	if [ "$DEBUG" = "0" -a "$DRY_RUN" = "0" ]; then
-    if ! echo $$ > "$lock"; then
-      echo "$s: ERR: Can't create $lock"
-      return 2
-    fi
-	fi
+# root 27.06.19 	if [ "$DEBUG" = "0" -a "$DRY_RUN" = "0" ]; then
+# root 27.06.19     if ! echo $$ > "$lock"; then
+# root 27.06.19       echo "$s: ERR: Can't create $lock"
+# root 27.06.19       return 2
+# root 27.06.19     fi
+# root 27.06.19 	fi
 
   #
   # Dirs
@@ -203,7 +204,7 @@ backup_dirs() {
   #
   IFS=$'\n'
   for d in $(sed "s/\([' ]\)/\\\\\\1/g" <<< "$dirs"); do
-    if is_locahost $s; then
+    if is_localhost $s; then
       ssh_dirs="$ssh_dirs \"$d\""
     else
       ssh_dirs="$ssh_dirs $s:\"$d\""
@@ -253,7 +254,7 @@ get_dirs() {
   [ -z "$DIRS" ] && return 1
 
   declare cmd="ssh $SSH_OPT -q -o ConnectTimeout=$CONN_TIMEOUT $s"
-  is_locahost $s && cmd="bash -c"
+  is_localhost $s && cmd="bash -c"
 
   declare exit=0;
   [ $DEBUG -gt 0 -o $DRY_RUN -gt 0 ] && exit=1
@@ -395,6 +396,12 @@ which realpath > /dev/null || realpath() {
 
 	cd "$pwd_bak"
 }
+
+#--------------------------------------
+# Include
+#--------------------------------------
+#cd "$(dirname "$0")"
+. "$(dirname "$0")"/../etc/profile || exit
 
 #--------------------------------------
 # Args
diff --git a/etc/profile b/etc/profile
--- a/etc/profile
+++ b/etc/profile
@@ -16,3 +16,52 @@ backup_servers_post_logs() {
     nb_api_post_host_info key=backup_servers.$host.dirs "val=$dirs"
   done
 }
+
+backup_servers_create_lock() {
+  #
+  # Check Lock
+  #
+  declare lock="${1:?Usage: backup_servers_create_lock LOCK_FILE}"
+  declare preff; [ $# -gt 0 ] && preff="$2"
+
+	if [ -e "$lock" ] ; then
+  	declare pid=`cat "$lock"`
+
+  	if [[ -z `ps -p $pid | sed 1d` ]]; then
+   	 echo "${preff}WARN: delete old lock $lock, pid $pid is not running"
+   	 rm "$lock"
+
+  	else
+    	echo "${preff}ERR: $lock already exists!"
+    	return 2
+
+  	fi
+  fi
+
+  if ! echo $$ > "$lock"; then
+    echo "$s: ERR: Can't create $lock"
+    return 2
+  fi
+
+  return 0
+}
+
+backup_servers_log_run_confs() {
+	declare LOG_DIR="${1:?Usage: backup_servers_log_run_confs LOG_DIR CONF1 CONF2 ... Run *.conf files in current directory}"; shift
+	[ -e "$LOG_DIR" ] || mkdir -vp "$LOG_DIR"
+
+	for conf in $@; do
+		[ -e ${conf}.conf ] || continue
+		#echo "$conf"; continue
+		#echo backup_servers --conf ${conf}.conf --debug; continue
+
+  	backup_servers_create_lock "$LOG_DIR/$conf.lock" || return
+
+		#backup_servers --conf ${conf}.conf; continue
+
+		backup_servers --conf ${conf}.conf > $LOG_DIR/${conf}.log && \
+			backup_servers_post_logs $LOG_DIR/${conf}.log >/dev/null 2>&1
+
+		rm "$LOG_DIR/$conf.lock"
+	done
+}
